ckeditor/ckeditor5-undo

src/undo.js
=> Hidden the button label. Closes #16.

src/undo.js
Fixes: https://github.com/ckeditor/ckeditor5/issues/211
Related to:
- https://github.com/ckeditor/ckeditor5-utils/pull/49
- https://github.com/ckeditor/ckeditor5-ui-default/pull/32
- https://github.com/ckeditor/ckeditor5-typing/pull/25
- https://github.com/ckeditor/ckeditor5-theme-lark/pull/22
- https://github.com/ckeditor/ckeditor5-engine/pull/530
- https://github.com/ckeditor/ckeditor5-delete/pull/13
- https://github.com/ckeditor/ckeditor5-basic-styles/pull/9
=> Changed const to lower case.

src/undo.js
Fixes https://github.com/ckeditor/ckeditor5-ui-default/issues/30
Depends on https://github.com/ckeditor/ckeditor5-ui-default/pull/31
=> Removed noText attribute from button.

tests/manual/undo.js
Fixes: https://github.com/ckeditor/ckeditor5-typing/issues/17
Depends on: https://github.com/ckeditor/ckeditor5-typing/pull/24
=> Fixed tests after package merged.

src/undocommand.js, tests/redocommand.js, tests/undocommand.js
Changes required by https://github.com/ckeditor/ckeditor5-engine/issues/480 and it's related PR: https://github.com/ckeditor/ckeditor5-engine/pull/537
=> Fixed: changes required by ckeditor5-engine#480.

tests/redocommand.js, tests/undocommand.js, tests/undoengine-integration.js
=> Changed name and order of arguments when using Batch methods

src/undocommand.js
=> Fixes: required by changes in engine.model.

src/undocommand.js, tests/undocommand.js
=> Fixes required by ckeditor5-engine/t/518.

src/basecommand.js, src/undo.js, src/undoengine.js, tests/basecommand.js, tests/redocommand.js, tests/undo.js, tests/undocommand.js, tests/undoengine-integration.js, tests/undoengine.js
=> Changed paths and docs to use ckeditor5-core package

src/undo.js
=> t/29: Removed ui.button.ButtonModel#iconAlign attribute from Button models.

src/basecommand.js, src/redocommand.js, src/undocommand.js, src/undoengine.js, tests/redocommand.js, tests/undocommand.js, tests/undoengine.js
=> T/12 Redo: make better selection restoring.

.jshintrc, tests/.jshintrc, tests/manual/undo.js, tests/undo.js
=> Turn JSHint browser setting to false.

tests/undoengine-integration.js
Fixes https://github.com/ckeditor/ckeditor5-engine/issues/306
Depends on: https://github.com/ckeditor/ckeditor5-engine/pull/554
=> Refactored model utils.

tests/manual/undo.html
=> Fixed path to ckeditor.css

src/undo.js, tests/undo.js
=> Implemented tooltips with keystroke information next to Undo and Redo buttons

.travis.yml, README.md, package.json
=> Initial configuration for Travis

src/undo.js, tests/undo.js
Closes #45.
Requires https://github.com/ckeditor/ckeditor5-ui/pull/100.
=> t/45: Updated undo after the removal of Controller class.

src/undo.js, tests/undo.js
=> t/49: MVC refactoring followups

src/basecommand.js, tests/undoengine-integration.js
Fixes #51. Requires https://github.com/ckeditor/ckeditor5-engine/pull/680.
=> Updated usage of DataController's methods

src/basecommand.js, src/redocommand.js, src/undocommand.js
Please test and merge after https://github.com/ckeditor/ckeditor5-engine/pull/727
=> Changed: use engine.model.delta.transformDeltaSets instead of providing own algorithm.

tests/undoengine-integration.js
Internal: Integration test for https://github.com/ckeditor/ckeditor5-engine/pull/892.
=> Integration test for undo/redo bug.

src/redocommand.js, src/undocommand.js
Internal: Fixed some imports (changes required by ckeditor5-engine#940).
=> Changed: Fixed import.

tests/undoengine-integration.js
Tests: additional undo integration tests.
---
These are some additional tests connected with issue https://github.com/ckeditor/ckeditor5-engine/issues/1051 (PR https://github.com/ckeditor/ckeditor5-engine/pull/1052).
=> Tests: additional undo integration tests.

tests/undoengine-integration.js
Tests: Additional integration tests.
---
For https://github.com/ckeditor/ckeditor5-engine/issues/1053
=> Tests: additional integration tests.

tests/undoengine-integration.js
Tests: added integration test.
---
For https://github.com/ckeditor/ckeditor5-engine/issues/1055
=> Tests: added integration test

package.json, tests/undoengine-integration.js
Tests: added integration tests.
----
Apart of adding additional test I also refactored the whole suite so enabling plugins is easier.
=> T/ckeditor5 engine/1065 Tests: added integration tests.

tests/undoengine-integration.js
Tests: Added a new test for undoing split delta.
---
Requires https://github.com/ckeditor/ckeditor5-engine/pull/1150
=> Tests: Added a new test for undoing split delta.

tests/undoengine-integration.js
Tests: Added new undo integration test.
=> Tests: Added new undo integration test.

src/undoengine.js, tests/undoengine-integration.js
Other: Changes after model events refactor in ckeditor5-engine.
=> Changes after model events refactor in ckeditor5-engine

tests/undoediting-integration.js
Internal: Align to changes made in DocumentSelection. See https://github.com/ckeditor/ckeditor5-engine/pull/1343.
=> Update tests after changes in DocumentSelection

tests/manual/undo.js
Other: Align code to the changes in naming UI components & commands.
---
* Minor PR - Check: https://github.com/ckeditor/ckeditor5-alignment/pull/25.
=> Other: Align code to the changes in naming UI components & commands.

tests/undoediting-integration.js
Other: Rename `setMarker` to `addMarker`.
=> T/ckeditor engine/1299

tests/redocommand.js, tests/undocommand.js
Tests: Fixed tests broken by https://github.com/ckeditor/ckeditor5-core/pull/135: Editor#destroy waits for the initialization.
=> Fixed failing tests.

tests/undoediting-integration.js
Internal: Align code to the API changes (selection post-fixer).
---
* Part of engine PR: https://github.com/ckeditor/ckeditor5-engine/pull/1450
=> Internal: Align code to the API changes (selection post-fixer).

tests/redocommand.js, tests/undocommand.js, tests/undoediting-integration.js
Tests: Unskip skipped tests.
---
*For example – encountered issues, assumptions you had to make, other affected tickets, etc.*
=> Unskip skipped tests.

src/basecommand.js
Internal: Aligned to changes in ckeditor5-engine.
=> Internal: Aligned to changes in ckeditor5-engine

tests/undocommand.js
Tests: Aligned to changes in ckeditor5-engine.
=> Tests: Aligned to changes in ckeditor5-engine
